services:
  db:
    container_name: postgres-StudentManagement
    image: postgres:18rc1
    environment:
      POSTGRES_USER: visura
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
